### ISSUE TITLE
Error with group names contains '-' character

### ISSUE THREAD

**Issue by ghost** [lamps/redmine_group_assignee#3]
Dear,

I found that your plugin is very useful, it helps to reduce load for admin to manage groups.
However, I got the following error with group names contains '-' character:
###### 

ActionView::TemplateError (`@test-01' is not allowed as an instance variable name) on line #1 of vendor/plugins/redmine_group_assignee/app/views/groupext/_form.html.erb:
<%= error_messages_for @group %>
<div class="box tabular">

<p><%= f.text_field :lastname, :label => :field_name %></p>

vendor/plugins/redmine_group_assignee/app/views/groupext/_form.html.erb:1
vendor/plugins/redmine_group_assignee/app/views/groupext/_general.html.erb:2
###### 

Regards,

**Comment by lamps** [comment]
hi
You which version to use?
if have 1.3.x, 
1. redmine_group_assignee / app / views / groupext / _form.html.erb file (This file must be modified)
        - 1 line is delete or replace <%= f.error_messages %> 
2. rake db:migrate_plugins RAILS_ENV=production
3. service restart..

_form.html.erb
<%= f.error_messages %>

<div class="box tabular">
  <p><%= f.text_field :lastname, :label => :field_name %></p>
  <% @group.custom_field_values.each do |value| %>
    <p><%= custom_field_tag_with_label :group, value %></p>
  <% end %>
</div>


Sorry, but I should not have file attachments
have a good time ^^

**Comment by lamps** [comment]
source link
https://github.com/lamps/redmine_group_assignee/blob/e1972e0dd794584afba5ed0586e02b509e4ccdaf/app/views/groupext/_form.html.erb

**Comment by ghost** [comment]
Hi,

I got it works like a charm. Thank you so much :)

Best regards,
